export const COMPETITOR_KEYWORDS_CATEGORY = {
  dubaiUae: [
    'dubai tour package from ahmedabad',
    'dubai tour packages from vadodara',
    'dubai tour packages from surat',
    'dubai tour packages from delhi / mumbai',
    'dubai desert safari tour packages from ahmedabad',
    'burj khalifa emirates mall holiday packages',
    'ferrari world abu dhabi theme park tour package',
    'dubai city dragon mall shopping tour',
    'dubai miracle garden & global village combo tour',
    'dubai marina dhow cruise & luxury yacht party',
    'dubai atlantis the palm resort luxury stay package',
    'dubai with lapita resort family vacation package',
    'diwali dubai with abu dhabi 6 nights 7 days group tour',
    'dubai new year family vacation packages',
    'dubai shopping festival special group tour',
    'dubai 4 nights 5 days budget holiday package',
    'dubai 5 nights 6 days deluxe family tour package',
    'dubai 6 nights 7 days all inclusive luxury tour',
    'dubai tourist visa guide for indians with package',
    'cities/dubai/tours',
    'cities/abu dhabi/tours',
    'cities/dubai/things to do',
    'cities/abu dhabi/things to do',
    'tours/luxurious delights trip to dubai abu dhabi',
    'tours/classic trip to yas island and abu dhabi',
    'tours/amazing dubai and abu dhabi tour package',
    'tours/highlights of abu dhabi',
    'tours/dubai abu dhabi luxury honeymoon escape',
    'tours/luxurious family getaway to dubai and abu dhabi',
    'tours/dubai couple luxury package',
    'tours/luxurious escape to dubai for family',
  ],
  gujaratSpecialTeerth: [
    'statue of unity tour package',
    'rann with gujarat tour package',
    'rann with sasangir tour package',
    'gujarat multicity tour package',
    '1 n ahmedabad 2 n dwarka 1 n somnath 1 n diu 1 n junagadh 1 n bhavnagar tour package',
    '2 n dwarka 1 n somnath 1 n diu 1 n sasan gir 1 n junagadh tour package',
    '1 n jamnagar 1 n dwarka 1 n somnath 1 n sasan gir 1 n bhavnagar tour package',
    '1 n ahmedabad 2 n dwarka 1 n somnath 1 n bhavnagar tour package',
    'dwarka somnath tour package',
    '1 n jamnagar 1 n dwarka 1 n somnath 1 n diu 1 n sasan gir 1 n statue of unity tour package',
    'gujarat with rann utsav statue of unity tour package',
    'dwarka somnath group 3n 4d tour package',
    'dwarka porbandar somnath 04 days tour package',
    'ahmedabad city tour package',
    'statue of unity 01 night ahmedabad2 tour package',
    'rann utsav 1 night 2 day tour package',
    'jalesh cruise with diu inside cabin tour package',
    'polo forest daily departures from ahmedabad tour package',
    'rann utsav 2 night 3 day tour package',
    'ayodhya from ahmedabad gujarat tour package',
    'dwarka somnath junagadhgirnar tour package',
    'pilgrimage places of gujarat 05 days tour package',
    'best indian honeymoon from ahmedabad tour package',
    'best international honeymoon from ahmedabad tour package',
    'kailash mansarovar yatra subsidy by gujarat government 2025 tour package',
    'affordable dubai from ahmedabad for families tour package',
    'jaisalmer from ahmedabad desert getaway tour package',
    'rann with gujarat from ahmedabad tour package',
    'ahmedabad to prayagraj mahakumbh 2025 gsrtc volvo bus tour package',
    'ahmedabad to prayagraj flights for mahakumbh mela 2025 tour package',
    'explore paradise goa from ahmedabad tour package',
    'kutch rann utsav gujarat tour package',
    'rann of kutch gujarat travel guide 2026 tour package',
    'ambaji with dharoi dam & vadnagar tour package',
    'rann utsav 2024 2025 desert festival of gujarat tour package',
    'rann festival booking online at kutch gujarat rann utsav tour package',
    'singapore thailand malaysia from ahmedabad gujarat india tour package',
    'switzerland from ahmedabad special tour package',
    'char dham yatra chardham yatra from ahmedabad tour package',
    'kashmir from ahmedabad explore tour package',
    'dwarka somnath best dwarka somnath from ahmedabad tour package',
    'polo forest gujarat tour package',
    'himachal shimla kullu manali from ahmedabad tour package',
  ],
  spiritualYatras: [
    'diwali divine ayodhya yatra prayagraj kashi yatra package',
    'nilkanth varni south india divine yatra yatra package',
    'puri bhubaneshwar kolkata group yatra package',
    'adi kailash 2026 group depature yatra yatra package',
    'ashtavinayak yatra yatra package',
    'mahakaleshwar omkareshwar tour2 yatra package',
    'khajuraho varanasi yatra package',
    'chappaiya ayodhya prayagraj varanasi yatra package',
    'chennai with tirupati temple yatra package',
    'chappaiya ayodhya prayagraj varanasi muktinath pashupatinath pokhra kathmandu yatra package',
    'mallikarjuna jyotirlinga yatra with hyderabad yatra package',
    'explore southern gems with rameshwaram yatra package',
    'shri jagannath puri yatra with gopalpur yatra package',
    'holy triangle ayodhya prayagraj banaras yatra package',
    'ganga sagar with puri yatra package',
    'divine mahakal madhya pradesh yatra package',
    'jagannath puri yatra package',
    'ayodhya to varanasi where faith comes alive yatra package',
    'do dham yatra in himalaya yatra package',
    'char dham yatra in himalaya yatra package',
    'chardham yatra yatra package',
    'mahakaleshwar omkareshwar yatra package',
    'tirupati balaji darshan yatra package',
    'amarnath yatra by helicopter yatra package',
    'kedarnath badrinath darshan yatra package',
    'kailash mansarovar yatra usa yatra package',
    'chardham yatra from usa nri yatra package',
    'chardham yatra from uk australia yatra package',
    'chardham yatra from canada yatra package',
    'kailash mansarovar yatra 2025 with a direct flight yatra package',
    'chardham yatra 2025 registration date opening date thing to know yatra package',
    'booking the ram mandir ayodhya yatra package',
    'mystical odyssey exploring the top chardham yatra yatra package',
    'unlocking the mysteries of amarnath yatra yatra package',
    'chardham yatra best time to visit yatra package',
    'exploring chardham yatra for pilgrims yatra package',
    'complete chardham yatra in 11 days yatra package',
    'kailash mansarovar and chhota kailash yatra religious summer journeys yatra package',
    'kailash mansarovar yatra 2025 the adventure religious nation yatra package',
    'tours/vaishno devi tour package from mumbai',
    'tours/spiritual magic of south india',
  ],
  topDomesticIndia: [
    'diwali scenic himachal domestic package',
    'paradise on earth diwali kashmir domestic package',
    'diwali goa escape domestic package',
    'summer escape to himachal domestic package',
    'himachal crafted for couples domestic package',
    'banglore with ooty kodaikanal domestic package',
    'banglore with coorg domestic package',
    'northeast paradise domestic package',
    'explore sikkim where the himalayas touch your soul domestic package',
    'discover sikkim darjeeling together domestic package',
    'short sweet honeymoon in andaman domestic package',
    'andaman romance special port blair 2 nights havelock 2 nights domestic package',
    'karnataka 6n 7d domestic package',
    'kashmir delight domestic package',
    'special kerala cochin to cochin domestic package',
    'udaipur kumbhalgarh 03n 04d domestic package',
    'sikkim gangtok domestic package',
    'bangalore mysore ooty kodaikanal rameshwar kanyakumari domestic package',
    'natural kerala domestic package',
    'glimpse of leh ladakh domestic package',
    'andaman retreat domestic package',
    'rajasthan domestic package',
    'snow shikara soulmates kashmir honeymoon vibes domestic package',
    'explore south indias soul kerala kanyakumari domestic package',
    'kerala honeymoon where romance meets nature domestic package',
    'kerala gods own country domestic package',
    'udaipur 02n 03d domestic package',
    'category/india /kashmir 8d domestic package',
    'category/india /goa domestic package',
    'category/india /south /tamilnadu domestic package',
    'category/india /karnataka domestic package',
    'category/india /leh ladakh domestic package',
    'category/india /kashmir domestic package',
    'category/india /sikkim darjeeling domestic package',
    'category/india /andaman domestic package',
    'category/india /rajasthan domestic package',
    'category/india /kerala domestic package',
    'category/india /himachal domestic package',
    'karnataka monsoon best places to explore domestic package',
    'luxury kerala for a premium experience domestic package',
    'why kashmir is the perfect summer destination domestic package',
    'luxury on a budget goa domestic package',
    'romantic retreats couple friendly goa domestic package',
    'capturing the beauty of kashmir during winter domestic package',
    'honeymoon kerala come and feel the natural sparkle domestic package',
    'kerala for 3 nights 4 days domestic package',
    'things to consider before booking kullu manali domestic package',
    '7 tourist attractions in kerala domestic package',
    'budget travel tips for himachal pradesh domestic package',
    '15 must visit places in kullu manali domestic package',
    'best places to visit in ladakh domestic package',
    'things to do in goa domestic package',
    'things to do in rajasthan desert safari domestic package',
    'best place to visit in ladakh domestic package',
    'things to do in kerala backwaters hills beaches domestic package',
    'best place to visit in rajasthan domestic package',
    'best places to visit in kerala domestic package',
    'best places to visit in andaman domestic package',
    'best places to visit in manali domestic package',
    'best places to visit in goa domestic package',
    'andaman and nicobar honeymoon paradise domestic package',
    'manali hill station destination domestic package',
    'enjoy honeymoon at kerala domestic package',
    'kashmir honeymoon domestic package',
    'goa honeymoon domestic package',
    'cities/ladakh/tours',
    'cities/lahaul spiti/tours',
    'cities/kashmir/tours',
    'states/kerala/tours',
    'states/andaman and nicobar islands/tours',
    'states/north east india/tours',
    'states/sikkim/tours',
    'states/meghalaya/tours',
    'states/rajasthan/tours',
    'states/himachal pradesh/tours',
    'cities/manali/tours',
    'states/uttarakhand/tours',
    'cities/darjeeling/tours',
    'states/kerala/tags/honeymoon',
    'cities/kashmir/tags/honeymoon',
    'states/andaman and nicobar islands/tags/honeymoon',
    'states/sikkim/tags/honeymoon',
    'states/meghalaya/tags/honeymoon',
    'states/rajasthan/tags/honeymoon',
    'cities/ladakh/tags/honeymoon',
    'cities/munnar/tags/honeymoon',
    'cities/manali/tags/honeymoon',
    'cities/shimla/tags/honeymoon',
    'cities/darjeeling/tags/honeymoon',
    'cities/nainital/tags/honeymoon',
    'cities/ooty/tags/honeymoon',
    'states/kerala/tags/family tours',
    'cities/kashmir/tags/family tours',
    'states/andaman and nicobar islands/tags/family tours',
    'states/rajasthan/tags/family tours',
    'states/sikkim/tags/family tours',
    'states/meghalaya/tags/family tours',
    'cities/ladakh/tags/family tours',
    'states/himachal pradesh/tags/family tours',
    'cities/manali/tags/family tours',
    'cities/shimla/tags/family tours',
    'states/uttarakhand/tags/family tours',
    'cities/darjeeling/tags/family tours',
    'cities/ooty/tags/family tours',
    'cities/kaziranga/tours',
    'south india tour packages',
    'regions/golden triangle/tours',
    'packages/shimla manali',
    'tours/fall in love with rajasthan',
    'tours/golden triangle tour 2',
    'tours/udaipur jodhpur jaisalmer tour package',
    'tours/jaipur bikaner jaisalmer jodhpur udaipur tour package',
    'tours/udaipur mount abu tour package from jaipur',
    'tours/jaipur udaipur sightseeing tour with jodhpur',
    'tours/best of kerala',
    'tours/kerala delight with houseboat stay',
    'tours/kerala couples delight with honeymoon freebies',
    'tours/exotic kerala with untouched coast of kanyakumari',
    'tours/experience kerala tour',
    'tours/kashmir honeymoon tour package',
    'tours/charistmatic private kashmir family tour package',
    'tours/kashmir tour package with doodhpathri',
    'tours/blissful 7 days kashmir honeymoon tour',
    'tours/unforgettable luxurious honeymoon in kashmir',
  ],
  adventureBiking: [
    'leh ladakh bike trip',
    'cities/lahaul spiti/tags/biking',
    'tours/ladakh adventure expedition with turtuk',
    'tours/7d 6n leh ladakh bike trip',
    'tours/private 7 days leh ladakh sightseeing tour',
    'tours/overland journey to ladakh',
    'tours/ladakh on bike',
    'tours/leh ladakh bike tour',
    'tours/spiti valley tour package from chandigarh',
    'tours/spiti tour in himachal from delhi',
    'tours/trans himalayan expedition',
    'tours/spiti winter tour',
    'tours/spiti valley tour package from delhi',
    'tours/kinnaur valley tour from chandigarh',
  ],
  internationalOutbound: [
    'cherry blossom of japan 2027 08 nights 09 days international package',
    'diwali thailand 6n7d 11 nov 2026 international package',
    'diwali himalayan bhutan bliss international package',
    'diwali bali 07 nights 08 days fix departure ex amd 10 nov 2026 international package',
    'wonders of japan international package',
    'experience japan international package',
    'azerbaijan baku2 international package',
    'sri lanka international package',
    'sail explore discover singapore malaysia cruise international package',
    'singapore sparkle malacca heritage johor bahru charm international package',
    'baps paris and swiss delight international package',
    'baps european delights mandir international package',
    'baps mandir paris international package',
    'singapore malaysia with cruise luxury cruise international package',
    'discover thailand where every moment feels magical international package',
    'grand europe international package',
    'european delights international package',
    'essence of europe international package',
    'european gems international package',
    'swiss paris delight international package',
    'eastern europe international package',
    'swipe to see why nepal in 8 days hits different international package',
    'nepal for the real explorers international package',
    'japan with seoul cherry blossom international package',
    'two emirates one smart deal dubai with abu dhabi international package',
    'sail into forever a singapore cruise romance international package',
    'honeymoon in heaven bali edition international package',
    'diwali dubai with abu dhabi 09 nov 11 nov 06n07d international package',
    'blooming japan cherry blossom special international package',
    'dubai abu dhabi where luxury lives international package',
    'diwali singapore with malaysia 06 nights 07 days 08 nov 2026 international package',
    'maldives taj exotica resort spa international package',
    'dubai with abu dhabi international package',
    'japan cherry blossom international package',
    'beauty in northern vietnam international package',
    'classic sri lanka international package',
    'premium dubai international package',
    'simply bali international package',
    'bali bliss adventurous to paradise international package',
    'dubai super saver international package',
    'experience autumn in japan international package',
    'luxury bali escape international package',
    'discover of bhutan international package',
    'beautiful mauritius international package',
    'turkey international package',
    'best of greece international package',
    'scenic japan international package',
    'explore the magic of bali international package',
    'travel to vietnam international package',
    'thailand glimpse international package',
    'singapore malaysia international package',
    'dubai with lapita a perfect blend international package',
    'royal bhutan international package',
    'magical bhutan international package',
    'georgia international package',
    'vietnam international package',
    'fascinating europe international package',
    'exclusive europe with london international package',
    'european highlights international package',
    'regions/europe/tours',
    'countries/switzerland/tours',
    'countries/italy/tours',
    'countries/france/tours',
    'countries/turkey/tours',
    'countries/iceland/tours',
    'countries/usa/tours',
    'countries/norway/tours',
    'countries/finland/tours',
    'countries/kenya/tours',
    'countries/south africa/tours',
    'countries/japan/tours',
    'countries/mauritius/tours',
    'countries/new zealand/tours',
    'countries/egypt/tours',
    'countries/australia/tours',
    'countries/thailand/tours',
    'countries/singapore/tours',
    'states/bali state/tours',
    'countries/vietnam/tours',
    'countries/malaysia/tours',
    'countries/maldives/tours',
    'countries/bhutan/tours',
    'countries/srilanka/tours',
    'countries/qatar/tours',
    'states/bali state/tags/honeymoon',
    'countries/maldives/tags/honeymoon',
    'regions/europe/tags/honeymoon',
    'countries/switzerland/tags/honeymoon',
    'cities/paris/tags/honeymoon',
    'countries/turkey/tags/honeymoon',
    'cities/dubai/tags/honeymoon',
    'countries/thailand/tags/honeymoon',
    'countries/singapore/tags/honeymoon',
    'countries/vietnam/tags/honeymoon',
    'countries/malaysia/tags/honeymoon',
    'countries/japan/tags/honeymoon',
    'countries/greece/tags/honeymoon',
    'countries/mauritius/tags/honeymoon',
    'countries/seychelles/tags/honeymoon',
    'tours/3 nights disney cruise from singapore',
    'regions/masai mara national reserve/tours',
    'regions/scandinavia/tours',
    'countries/africa/tours',
    'countries/philippines/tours',
    'countries/seychelles/tours',
    'singapore malaysia thailand tour packages',
    'packages/singapore malaysia',
    'tours/scenic iceland with diamond circle',
    'tours/iceland group tour free pernal museum tickets',
    'tours/highlights of iceland with golden circle tour',
    'tours/discover iceland with free whale watching tour',
    'tours/icelandic wonders with free northern lights tour',
    'tours/glimpse of iceland',
    'tours/explore japan',
    'tours/jewels of japan mount fuji special',
    'tours/enchanting japan',
    'tours/japan extravaganza',
    'tours/iconic japan with mount fuji',
    'tours/best of japan',
    'tours/bali and singapore honeymoon package',
    'tours/discover singapore',
    'tours/glimpse of singapore',
    'tours/captivating singapore and malaysia tour',
    'tours/enchanting singapore tour package',
    'tours/journey to singapore',
    'tours/nooe maldives kunaavashi resort',
    'tours/cocoon maldives',
    'tours/medhufushi island resort maldives beach villa water villa',
    'tours/reethi faru resort maldives',
    'tours/olhuveli beach spa resort maldives',
    'tours/centara mirage lagoon maldives',
    'tours/north sikkim tour of 6 days',
    'tours/gangtok darjeeling tour',
    'tours/gangtok yumthang and lachung',
    'tours/sikkim darjeeling tour package',
    'tours/unexplored arunachal tour package tawang special',
    'tours/north sikkim tour with pelling',
    'tours/best of thailand',
    'tours/an odyssey to thailand bangkok phuket krabi',
    'tours/bangkok pattaya phuket tour package',
    'tours/phuket and krabi tour package from delhi',
    'tours/5 nights and 6 days tour of thailand',
    'tours/thailand tour package',
    'tours/taste the north and south of vietnam',
    'tours/vietnam explorer north south central',
    'tours/rediscover vietnam a complete tour package',
    'tours/a combined vietnam cambodia honeymoon tour',
    'tours/vietnam sightseeing tour',
    'tours/cambodia vietnam tour package from india',
    'tours/best of scandinavian with norway',
    'tours/norway scenic escape',
    'tours/norway family adventure',
    'tours/scenic scandinavia with free copenhagen canal cruise',
    'tours/norwegian escapade northern lights with norway in a nutshell',
    'tours/capitals of scandinavia with free fjords cruise',
    'tours/rediscover bali in 6 days',
    'tours/uncover bali',
    'tours/bali couple tour',
    'tours/bali honeymoon special',
    'tours/highlights of bali',
    'tours/bali honeymoon delight tour package',
    'tours/grand group tour to usa coastal cities',
    'tours/usa group tour to california and vegas',
    'tours/usa east coast group tour with niagara falls',
    'tours/glimpse of new york usa with circle line cruise',
    'tours/usa group tour nyc dc philly the falls',
    'tours/coastal california self drive expedition',
    'tours/glimpse of bhutan tour package',
    'tours/bhutan tour from india 5n 6d',
    'tours/experience bhutan with amankora lodges',
    'tours/nepal bhutan tour package',
    'tours/8 days bhutan tour with paro taktsang',
    'tours/7 days bhutan tour from india with dochu la pass',
  ],
  cityThingsToDo: [
    'countries/singapore/things to do',
    'cities/bangkok/things to do',
    'cities/phuket/things to do',
    'cities/pattaya/things to do',
    'cities/kuala lumpur/things to do',
    'cities/langkawi/things to do',
    'states/bali state/things to do',
    'cities/ho chi minh/things to do',
    'cities/amsterdam/things to do',
    'cities/paris/things to do',
    'cities/barcelona/things to do',
    'cities/london/things to do',
    'cities/istanbul/things to do',
    'cities/rome/things to do',
    'cities/venice/things to do',
    'cities/zurich/things to do',
    'cities/interlaken/things to do',
    'cities/prague/things to do',
    'cities/dubai/things to do',
    'cities/abu dhabi/things to do',
    'cities/new york city/things to do',
    'states/california/things to do',
    'cities/orlando/things to do',
    'cities/las vegas/things to do',
    'cities/goldcoast/things to do',
    'cities/sydney/things to do',
    'cities/melbourne/things to do',
    'cities/tokyo/things to do',
    'countries/hong kong/things to do',
  ],
  specialTourTypes: [
    'mice',
    'new zealand fixed departure special package',
    'luxury from historic tbilisi to chic batumi special package',
    'australia fixed departure itinerary special package',
    'start forever in paradise port blair havelock honeymoon moments special package',
    'seniors special america special package',
    'honeymoon special special package',
    'saurashtra darshan group special package',
    'northern lights adventure in iceland group departure 2026 special package',
    'india honeymoon special special package',
    'international honeymoon special special package',
    'Senior Special special package',
    'family special package',
    'best international honeymoon places to visit special package',
    'top 11 international honeymoon destinations special package',
    'top 10 best romantic international honeymoon destinations special package',
    'top 5 romantic destination of north india honeymoon special package',
    'canada honeymoon special special package',
  ],
};

export const ALL_COMPETITOR_KEYWORDS = Object.values(COMPETITOR_KEYWORDS_CATEGORY).flat();

import {
  THRILLOPHILIA_SPIRITUAL_KEYWORDS,
  THRILLOPHILIA_GUJARAT_KEYWORDS,
  THRILLOPHILIA_DOMESTIC_KEYWORDS,
  THRILLOPHILIA_INTERNATIONAL_KEYWORDS,
  THRILLOPHILIA_ALL_MASTER_SLUGS,
  TOTAL_THRILLOPHILIA_KEYWORD_COUNT,
} from './thrillophiliaMasterKeywords';

export {
  THRILLOPHILIA_SPIRITUAL_KEYWORDS,
  THRILLOPHILIA_GUJARAT_KEYWORDS,
  THRILLOPHILIA_DOMESTIC_KEYWORDS,
  THRILLOPHILIA_INTERNATIONAL_KEYWORDS,
  THRILLOPHILIA_ALL_MASTER_SLUGS,
  TOTAL_THRILLOPHILIA_KEYWORD_COUNT,
};
