export const COMPETITOR_KEYWORDS_CATEGORY = {
  dubaiUae: [
    'dubai tour package from ahmedabad',
    'dubai tour packages from vadodara',
    'dubai tour packages from surat',
    'dubai tour packages from delhi / mumbai',
    'dubai desert safari tour packages from ahmedabad',
    'burj khalifa emirates mall holiday packages',
    'ferrari world abu dhabi theme park tour package',
    'dubai city dragon mall shopping tour',
    'dubai miracle garden & global village combo tour',
    'dubai marina dhow cruise & luxury yacht party',
    'dubai atlantis the palm resort luxury stay package',
    'dubai with lapita resort family vacation package',
    'diwali dubai with abu dhabi 6 nights 7 days group tour',
    'dubai new year family vacation packages',
    'dubai shopping festival special group tour',
    'dubai 4 nights 5 days budget holiday package',
    'dubai 5 nights 6 days deluxe family tour package',
    'dubai 6 nights 7 days all inclusive luxury tour',
    'dubai tourist visa guide for indians with package',
  ],
  gujaratSpecialTeerth: [
    'statue of unity tour package',
    'rann with gujarat tour package',
    'rann with sasangir tour package',
    'gujarat multicity tour package',
    '1 n ahmedabad 2 n dwarka 1 n somnath 1 n diu 1 n junagadh 1 n bhavnagar tour package',
    '2 n dwarka 1 n somnath 1 n diu 1 n sasan gir 1 n junagadh tour package',
    '1 n jamnagar 1 n dwarka 1 n somnath 1 n sasan gir 1 n bhavnagar tour package',
    '1 n ahmedabad 2 n dwarka 1 n somnath 1 n bhavnagar tour package',
    'dwarka somnath tour package',
    '1 n jamnagar 1 n dwarka 1 n somnath 1 n diu 1 n sasan gir 1 n statue of unity tour package',
    'gujarat with rann utsav statue of unity tour package',
    'dwarka somnath group 3n 4d tour package',
    'dwarka porbandar somnath 04 days tour package',
    'ahmedabad city tour package',
    'statue of unity 01 night ahmedabad2 tour package',
    'statue of unity tour package',
    'rann utsav 1 night 2 day tour package',
    'jalesh cruise with diu inside cabin tour package',
    'polo forest daily departures from ahmedabad tour package',
    'rann utsav 2 night 3 day tour package',
    'ayodhya from ahmedabad gujarat tour package',
    'dwarka somnath junagadhgirnar tour package',
    'pilgrimage places of gujarat 05 days tour package',
    'sri lanka diwali from ahmedabad a complete travel guide tour package',
    'best indian honeymoon from ahmedabad tour package',
    'best international honeymoon from ahmedabad tour package',
    'kailash mansarovar yatra subsidy by gujarat government 2025 tour package',
    'affordable dubai from ahmedabad for families tour package',
    'jaisalmer from ahmedabad desert getaway tour package',
    'rann with gujarat from ahmedabad tour package',
    'ahmedabad to prayagraj mahakumbh 2025 gsrtc volvo bus tour package',
    'ahmedabad to prayagraj flights for mahakumbh mela 2025 tour package',
    'explore paradise goa from ahmedabad tour package',
    'kutch rann utsav gujarat tour package',
    'rann of kutch gujarat travel guide 2026 tour package',
    'ambaji with dharoi dam & vadnagar tour package',
    'rann utsav 2024 2025 desert festival of gujarat tour package',
    'rann festival booking online at kutch gujarat rann utsav tour package',
    'singapore thailand malaysia from ahmedabad gujarat india tour package',
    'switzerland from ahmedabad special tour package',
    'char dham yatra chardham yatra from ahmedabad tour package',
    'kashmir from ahmedabad explore tour package',
    'dwarka somnath best dwarka somnath from ahmedabad tour package',
    'polo forest gujarat tour package',
    'himachal shimla kullu manali from ahmedabad tour package',
  ],
  spiritualYatras: [
    'diwali divine ayodhya yatra prayagraj kashi yatra package',
    'nilkanth varni south india divine yatra yatra package',
    'puri bhubaneshwar kolkata group yatra package',
    'adi kailash 2026 group depature yatra yatra package',
    'ashtavinayak yatra yatra package',
    'mahakaleshwar omkareshwar tour2 yatra package',
    'khajuraho varanasi yatra package',
    'chappaiya ayodhya prayagraj varanasi yatra package',
    'chennai with tirupati temple yatra package',
    'chappaiya ayodhya prayagraj varanasi muktinath pashupatinath pokhra kathmandu yatra package',
    'mallikarjuna jyotirlinga yatra with hyderabad yatra package',
    'explore southern gems with rameshwaram yatra package',
    'shri jagannath puri yatra with gopalpur yatra package',
    'holy triangle ayodhya prayagraj banaras yatra package',
    'ganga sagar with puri yatra package',
    'divine mahakal madhya pradesh yatra package',
    'jagannath puri yatra package',
    'ayodhya to varanasi where faith comes alive yatra package',
    'do dham yatra in himalaya yatra package',
    'char dham yatra in himalaya yatra package',
    'chardham yatra yatra package',
    'mahakaleshwar omkareshwar yatra package',
    'tirupati balaji darshan yatra package',
    'amarnath yatra by helicopter yatra package',
    'kedarnath badrinath darshan yatra package',
    'kailash mansarovar yatra usa yatra package',
    'chardham yatra from usa nri yatra package',
    'chardham yatra from uk australia yatra package',
    'chardham yatra from canada yatra package',
    'kailash mansarovar yatra 2025 with a direct flight yatra package',
    'chardham yatra 2025 registration date opening date thing to know yatra package',
    'booking the ram mandir ayodhya yatra package',
    'mystical odyssey exploring the top chardham yatra yatra package',
    'unlocking the mysteries of amarnath yatra yatra package',
    'chardham yatra best time to visit yatra package',
    'exploring chardham yatra for pilgrims yatra package',
    'complete chardham yatra in 11 days yatra package',
    'kailash mansarovar and chhota kailash yatra religious summer journeys yatra package',
    'kailash mansarovar yatra 2025 the adventure religious nation yatra package',
  ],
  topDomesticIndia: [
    'diwali scenic himachal domestic package',
    'paradise on earth diwali kashmir domestic package',
    'diwali goa escape domestic package',
    'summer escape to himachal domestic package',
    'himachal crafted for couples domestic package',
    'banglore with ooty kodaikanal domestic package',
    'banglore with coorg domestic package',
    'northeast paradise domestic package',
    'explore sikkim where the himalayas touch your soul domestic package',
    'discover sikkim darjeeling together domestic package',
    'short sweet honeymoon in andaman domestic package',
    'andaman romance special port blair 2 nights havelock 2 nights domestic package',
    'karnataka 6n 7d domestic package',
    'kashmir delight domestic package',
    'special kerala cochin to cochin domestic package',
    'udaipur kumbhalgarh 03n 04d domestic package',
    'sikkim gangtok domestic package',
    'bangalore mysore ooty kodaikanal rameshwar kanyakumari domestic package',
    'natural kerala domestic package',
    'glimpse of leh ladakh domestic package',
    'andaman retreat domestic package',
    'rajasthan domestic package',
    'snow shikara soulmates kashmir honeymoon vibes domestic package',
    'explore south indias soul kerala kanyakumari domestic package',
    'kerala honeymoon where romance meets nature domestic package',
    'kerala gods own country domestic package',
    'udaipur 02n 03d domestic package',
    'category/india /kashmir 8d domestic package',
    'category/india /goa domestic package',
    'category/india /south /tamilnadu domestic package',
    'category/india /karnataka domestic package',
    'category/india /leh ladakh domestic package',
    'category/india /kashmir domestic package',
    'category/india /sikkim darjeeling domestic package',
    'category/india /andaman domestic package',
    'category/india /rajasthan domestic package',
    'category/india /kerala domestic package',
    'category/india /himachal domestic package',
    'karnataka monsoon best places to explore domestic package',
    'luxury kerala for a premium experience domestic package',
    'why kashmir is the perfect summer destination domestic package',
    'luxury on a budget goa domestic package',
    'romantic retreats couple friendly goa domestic package',
    'capturing the beauty of kashmir during winter domestic package',
    'honeymoon kerala come and feel the natural sparkle domestic package',
    'kerala for 3 nights 4 days domestic package',
    'things to consider before booking kullu manali domestic package',
    '7 tourist attractions in kerala domestic package',
    'budget travel tips for himachal pradesh domestic package',
    '15 must visit places in kullu manali domestic package',
    'best places to visit in ladakh domestic package',
    'things to do in goa domestic package',
    'things to do in rajasthan desert safari domestic package',
    'best place to visit in ladakh domestic package',
    'things to do in kerala backwaters hills beaches domestic package',
    'best place to visit in rajasthan domestic package',
    'best places to visit in kerala domestic package',
    'best places to visit in andaman domestic package',
    'best places to visit in manali domestic package',
    'best places to visit in goa domestic package',
    'andaman and nicobar honeymoon paradise domestic package',
    'manali hill station destination domestic package',
    'enjoy honeymoon at kerala domestic package',
    'kashmir honeymoon domestic package',
    'goa honeymoon domestic package',
  ],
  internationalOutbound: [
    'cherry blossom of japan 2027 08 nights 09 days international package',
    'diwali thailand 6n7d 11 nov 2026 international package',
    'diwali himalayan bhutan bliss international package',
    'diwali bali 07 nights 08 days fix departure ex amd 10 nov 2026 international package',
    'wonders of japan international package',
    'experience japan international package',
    'azerbaijan baku2 international package',
    'sri lanka international package',
    'sail explore discover singapore malaysia cruise international package',
    'singapore sparkle malacca heritage johor bahru charm international package',
    'baps paris and swiss delight international package',
    'baps european delights mandir international package',
    'baps mandir paris international package',
    'singapore malaysia with cruise luxury cruise international package',
    'discover thailand where every moment feels magical international package',
    'grand europe international package',
    'european delights international package',
    'essence of europe international package',
    'european gems international package',
    'swiss paris delight international package',
    'eastern europe international package',
    'swipe to see why nepal in 8 days hits different international package',
    'nepal for the real explorers international package',
    'japan with seoul cherry blossom international package',
    'two emirates one smart deal dubai with abu dhabi international package',
    'sail into forever a singapore cruise romance international package',
    'honeymoon in heaven bali edition international package',
    'diwali dubai with abu dhabi 09 nov 11 nov 06n07d international package',
    'blooming japan cherry blossom special international package',
    'dubai abu dhabi where luxury lives international package',
    'diwali singapore with malaysia 06 nights 07 days 08 nov 2026 international package',
    'maldives taj exotica resort spa international package',
    'dubai with abu dhabi international package',
    'japan cherry blossom international package',
    'beauty in northern vietnam international package',
    'classic sri lanka international package',
    'premium dubai international package',
    'simply bali international package',
    'bali bliss adventurous to paradise international package',
    'dubai super saver international package',
    'experience autumn in japan international package',
    'luxury bali escape international package',
    'discover of bhutan international package',
    'beautiful mauritius international package',
    'turkey international package',
    'best of greece international package',
    'scenic japan international package',
    'explore the magic of bali international package',
    'travel to vietnam international package',
    'thailand glimpse international package',
    'singapore malaysia international package',
    'dubai with lapita a perfect blend international package',
    'royal bhutan international package',
    'magical bhutan international package',
    'georgia international package',
    'vietnam international package',
    'fascinating europe international package',
    'exclusive europe with london international package',
    'european highlights international package',
    'category/international /dubai from vadodara international package',
    'category/international /dubai from surat international package',
    'category/international /georgia tbilisi international package',
    'category/international /baku international package',
    'category/international /asia /sri lanka international package',
    'category/international /africa /egypt international package',
    'category/international /maldives international package',
    'category/international /east europe international package',
    'category/international /central europe international package',
    'category/international /east europe/scotland international package',
    'category/international /east europe/greece international package',
    'category/international /east europe/turkey international package',
    'category/international /east europe/croatia international package',
    'category/international /central europe/switzerland paris international package',
    'category/international /central europe/denmark international package',
    'category/international /central europe/belgium international package',
    'category/international /central europe/iceland international package',
    'category/international /central europe/spain international package',
    'category/international /central europe/germany international package',
    'category/international /central europe/italy international package',
    'category/international /central europe/netherlands international package',
    'category/international /central europe/france international package',
    'category/international /central europe/uk united kingdom international package',
    'category/international /central europe/switzerland international package',
    'category/international /central europe/austria international package',
    'category/international /central europe/scandinavia international package',
    'category/international /asia /singapore malaysia thailand international package',
    'category/international /asia /singapore bali international package',
    'category/international /singapore malaysia international package',
    'category/international /asia /vietnam cambodia international package',
    'category/international /asia /malaysia international package',
    'category/international /asia /japan international package',
    'category/international /thailand international package',
    'category/international /asia /bali international package',
    'category/international /asia /singapore international package',
    'category/international /africa /seychelles international package',
    'category/international /africa /mauritius international package',
    'baps mandir paris opening 2026 complete visitor guide international package',
    'best 7 day thailand packages for indian couples in 2026 international package',
    'dubai a complete travelers guide international package',
    'dubais top 15 activities international package',
    'dubai tourist visa guide for indians international package',
    'luxuriously affordable honeymoon in bali international package',
    'top 11 places to visit in mauritius 2026 international package',
    'top 10 places and things to do in malaysia international package',
  ],
  specialTourTypes: [
    'new zealand fixed departure special package',
    'luxury from historic tbilisi to chic batumi special package',
    'australia fixed departure itinerary special package',
    'start forever in paradise port blair havelock honeymoon moments special package',
    'seniors special america special package',
    'honeymoon special special package',
    'saurashtra darshan group special package',
    'northern lights adventure in iceland group departure 2026 special package',
    'india honeymoon special special package',
    'international honeymoon special special package',
    'Senior Special special package',
    'family special package',
    'best international honeymoon places to visit special package',
    'top 11 international honeymoon destinations special package',
    'top 10 best romantic international honeymoon destinations special package',
    'top 5 romantic destination of north india honeymoon special package',
    'canada honeymoon special special package',
  ],
};

export const ALL_COMPETITOR_KEYWORDS = Object.values(COMPETITOR_KEYWORDS_CATEGORY).flat();
