// TRIP CUSTOMIZER MASTER SEARCH KEYWORDS INDEX
import {
  SPIRITUAL_KEYWORDS_INDEX,
  GUJARAT_KEYWORDS_INDEX,
  DOMESTIC_KEYWORDS_INDEX,
  INTERNATIONAL_KEYWORDS_INDEX,
  ALL_MASTER_KEYWORD_SLUGS,
  TOTAL_MASTER_KEYWORD_COUNT,
} from './masterKeywordsIndex';

export const MASTER_SEARCH_CATEGORIES = {
  dubaiUae: [
    'dubai tour package from ahmedabad',
    'dubai tour packages from vadodara',
    'dubai tour packages from surat',
    'dubai tour packages from delhi mumbai',
    'dubai desert safari tour packages',
    'burj khalifa emirates mall holiday packages',
    'ferrari world abu dhabi theme park tour package',
    'dubai city dragon mall shopping tour',
    'dubai miracle garden & global village combo tour',
    'dubai marina dhow cruise & luxury yacht party',
    'dubai atlantis the palm resort luxury stay package',
    'dubai with lapita resort family vacation package',
    'diwali dubai with abu dhabi 6 nights 7 days group tour',
    'dubai new year family vacation packages',
    'dubai shopping festival special group tour',
    'dubai 4 nights 5 days budget holiday package',
    'dubai 5 nights 6 days deluxe family tour package',
    'dubai 6 nights 7 days all inclusive luxury tour',
    'dubai tourist visa guide for indians with package',
  ],
  gujaratSpecialTeerth: [
    'statue of unity tour package',
    'rann with gujarat tour package',
    'rann with sasangir tour package',
    'gujarat multicity tour package',
    'dwarka somnath tour package',
    'gujarat with rann utsav statue of unity tour package',
    'dwarka somnath group 3n 4d tour package',
    'dwarka porbandar somnath 04 days tour package',
    'ahmedabad city tour package',
    'rann utsav 1 night 2 day tour package',
    'polo forest daily departures tour package',
    'rann utsav 2 night 3 day tour package',
    'ayodhya from gujarat tour package',
    'dwarka somnath junagadh girnar tour package',
    'pilgrimage places of gujarat 05 days tour package',
    'best indian honeymoon tour package',
    'best international honeymoon tour package',
    'jaisalmer desert getaway tour package',
    'explore paradise goa tour package',
    'kutch rann utsav gujarat tour package',
    'ambaji with dharoi dam & vadnagar tour package',
    'rann utsav desert festival of gujarat tour package',
    'switzerland special tour package',
    'char dham yatra tour package',
    'kashmir explore tour package',
    'dwarka somnath best tour package',
    'polo forest gujarat tour package',
    'himachal shimla kullu manali tour package',
  ],
  spiritualYatras: SPIRITUAL_KEYWORDS_INDEX.slice(0, 40),
  topDomesticIndia: DOMESTIC_KEYWORDS_INDEX.slice(0, 50),
  adventureBiking: [
    'leh ladakh bike trip package',
    'lahaul spiti biking tour package',
    'ladakh adventure expedition with turtuk',
    '7d 6n leh ladakh bike trip',
    'private 7 days leh ladakh sightseeing tour',
    'overland journey to ladakh',
    'spiti valley tour package from chandigarh',
    'spiti tour in himachal from delhi',
    'trans himalayan expedition',
    'spiti winter tour package',
    'spiti valley tour package from delhi',
    'kinnaur valley tour from chandigarh',
  ],
  internationalOutbound: INTERNATIONAL_KEYWORDS_INDEX.slice(0, 60),
  specialTourTypes: [
    'new zealand fixed departure special package',
    'australia fixed departure itinerary special package',
    'port blair havelock honeymoon moments special package',
    'seniors special america special package',
    'saurashtra darshan group special package',
    'northern lights adventure in iceland group departure 2026 special package',
    'india honeymoon special package',
    'international honeymoon special package',
    'family special package',
    'best international honeymoon places to visit special package',
    'top 11 international honeymoon destinations special package',
    'canada honeymoon special package',
  ],
};

export {
  SPIRITUAL_KEYWORDS_INDEX,
  GUJARAT_KEYWORDS_INDEX,
  DOMESTIC_KEYWORDS_INDEX,
  INTERNATIONAL_KEYWORDS_INDEX,
  ALL_MASTER_KEYWORD_SLUGS,
  TOTAL_MASTER_KEYWORD_COUNT,
};
